@startuml
actor TestCase
TestCase -> Jugador: usarCartaEspecial(posicion)
Jugador -> Mano: seleccionarCarta(posicion)
Mano --> Jugador: carta
Jugador -> Clima: usar()
Clima -> Seccion1: reducirPuntaje(valor)
Clima -> Seccion2: reducirPuntaje(valor)

@enduml